### ISSUE TITLE
Design Docs Review - Sample State

### ISSUE THREAD

**Issue by jliversi** [glhkang/prfctPX#2]
Great work on your sample state, here are my only notes:
- [x] Add a slice under entities for comments. Add `commentIds` arrays under photos and users
- [x] Add an array of `profilePhotos` under users (to track photos on their profile page).
- [x] Can `archived` (on photos) only exist in two states? If so, you should use a boolean for this (and should also change this to a boolean in your schema).

**Comment by glhkang** [comment]
Hey Josh,
Just a note: archived photos were not added to the `profile_photos` array (under users) as they will not show on on their profile page.
Otherwise everything else has been updated (also, yes to the boolean).
